name: Test

on: push
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: Test
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim
          nvim --version
      - name: Create directory and test.lua
        run: |
          mkdir -p "test"
          echo 'local function a()' >> "test/test.lua"
          echo  'local co = coroutine.running()' >> "test/test.lua"
          echo 'print("3")' >> "test/test.lua"
          echo 'vim.schedule(function ()' >> "test/test.lua"
          echo 'local str = "4"' >> "test/test.lua"
          echo 'coroutine.resume(co, 1)' >> "test/test.lua"
          echo 'print(str .. "5")' >> "test/test.lua"
          echo 'end)' >> "test/test.lua"
          echo 'print("6")' >> "test/test.lua"
          echo 'return coroutine.yield()' >> "test/test.lua"
          echo 'end' >> "test/test.lua"
          echo 'print("1")' >> "test/test.lua"
          echo 'print(coroutine.wrap(a)(), "243")' >> "test/test.lua"
          echo 'print("2")' >> "test/test.lua"
          echo 'end)' >> "test/test.lua"
          ls -la "test"
          cat "test/test.lua"
      - name: Run Neovim sourcing test.lua and exit
        run: |
          nvim --headless +'source test/test.lua' +qa
          echo 'Done'
      - name: Run Neovim sourcing test.lua and exit
        run: |
          nvim --headless +'source #test/test.lua' +qa
